# Generated by Django 6.0.6 on 2026-06-22 09:19

from django.db import migrations, models
from django.utils.text import slugify


def poblar_slugs(apps, schema_editor):
    Curso = apps.get_model('cursos', 'Curso')
    for curso in Curso.objects.all():
        curso.slug = slugify(curso.nombre)
        curso.save()


class Migration(migrations.Migration):

    atomic = False  # Evita conflicto de índice _like duplicado en PostgreSQL

    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="curso",
            name="slug",
            field=models.SlugField(blank=True, default='', unique=False),
            preserve_default=False,
        ),
        migrations.RunPython(poblar_slugs, migrations.RunPython.noop),
        migrations.RunSQL(
            "ALTER TABLE cursos_curso ADD CONSTRAINT cursos_curso_slug_key UNIQUE (slug);",
            "ALTER TABLE cursos_curso DROP CONSTRAINT IF EXISTS cursos_curso_slug_key;",
        ),
    ]
